### PR TITLE
WIP: 🐛 Fix missing files when listing large buckets

### PR DESCRIPTION
**Pull request by alexander-zierhut**
When listing huge buckets, some files are missing in the listing. 

- [ ] Tests have to be written to confirm the bug is fixed

Signed-off-by: AlexZierhut <alex@zierhut-it.de>

### CODE REVIEW

**Comment by alexander-zierhut** [comment]
We have been using the following patch as a workaround since months.

[akeeba_s3.patch.txt](https://github.com/akeeba/s3/files/9209793/akeeba_s3.patch.txt)

**Comment by nikosdion** [comment]
You are right about the problem being there but your solution is a bit of a hack which works on your use case but is generally a bad idea. Let me try refactoring that code and come up with a better way to implement this.

**Comment by nikosdion** [comment]
Please see commit https://github.com/akeeba/s3/commit/6448ddf99541f3ba50f97e373ceeb5bfd42a0167 for a better solution

**Comment by alexander-zierhut** [comment]
Hi @nikosdion thank you for your reply and commit. 

> but your solution is a bit of a hack which works on your use case

That is surely true. It's a simple patch to get things running which did a great job. Thank your for writing a proper solution with an actual test!

**Comment by nikosdion** [comment]
You're welcome :) Thank you for the heads up and Happy New Year!

**Pull request closed without merging**
